import importlib


MODULES = [
    "atlas.daily_brief",
    "atlas.mission",
    "atlas.ranking",

    "brain.atlas_brain",
    "brain.explanation_engine",

    "collector_intelligence.adapter_base",
    "collector_intelligence.adapter_registry",
    "collector_intelligence.adapters",
    "collector_intelligence.adapters.event_listing",
    "collector_intelligence.adapters.generic_article",
    "collector_intelligence.adapters.manual_text",
    "collector_intelligence.adapters.marketplace_listing",
    "collector_intelligence.adapters.retailer_product",
    "collector_intelligence.adapters.rss_item",
    "collector_intelligence.adapters.social_post",
    "collector_intelligence.adapters.structured_report",
    "collector_intelligence.aggregation_config",
    "collector_intelligence.aggregation_models",
    "collector_intelligence.aggregator",
    "collector_intelligence.category_profiles",
    "collector_intelligence.change_detection",
    "collector_intelligence.conflict_resolution",
    "collector_intelligence.connector_base",
    "collector_intelligence.connector_cache",
    "collector_intelligence.connector_config",
    "collector_intelligence.connector_models",
    "collector_intelligence.connector_parsing",
    "collector_intelligence.connector_pipeline",
    "collector_intelligence.connector_registry",
    "collector_intelligence.connector_scheduler",
    "collector_intelligence.connectors",
    "collector_intelligence.connectors.announcement_connector",
    "collector_intelligence.connectors.event_connector",
    "collector_intelligence.connectors.html_connector",
    "collector_intelligence.connectors.json_connector",
    "collector_intelligence.connectors.retailer_page_connector",
    "collector_intelligence.connectors.rss_connector",
    "collector_intelligence.connectors.xml_connector",
    "collector_intelligence.decision_engine",
    "collector_intelligence.detector",
    "collector_intelligence.enums",
    "collector_intelligence.evidence_ledger",
    "collector_intelligence.extraction",
    "collector_intelligence.finalization",
    "collector_intelligence.finalized_summary",
    "collector_intelligence.http_client",
    "collector_intelligence.identity_matching",
    "collector_intelligence.ingestion_config",
    "collector_intelligence.ingestion_fingerprinting",
    "collector_intelligence.ingestion_models",
    "collector_intelligence.ingestion_normalization",
    "collector_intelligence.ingestion_pipeline",
    "collector_intelligence.ingestion_validation",
    "collector_intelligence.models",
    "collector_intelligence.normalize",
    "collector_intelligence.opportunity_builder",
    "collector_intelligence.scoring",
    "collector_intelligence.scoring_config",
    "collector_intelligence.scoring_models",
    "collector_intelligence.signals",
    "collector_intelligence.source_models",
    "collector_intelligence.summary",

    "decision.decision_engine",

    "learning.engine",
    "learning.models",
    "learning.statistics",
    "learning.storage",

    "market.aggregator",
    "market.cache",
    "market.ebay",
    "market.ebay_live",
    "market.engine",
    "market.manual",
    "market.models",
    "market.pricecharting",
    "market.provider",
    "market.roi",
    "market.router",
    "market.stockx",
    "market.tcgplayer",

    "patterns.engine",
    "patterns.history",
    "patterns.matcher",
    "patterns.scorer",

    "popularity.engine",
    "popularity.models",
    "popularity.pokemon",

    "reasoning.confidence",
    "reasoning.engine",
    "reasoning.evidence",
    "reasoning.opportunity",
    "reasoning.resale",
    "reasoning.urgency",

    "scouts.base.atlas_scout",

    "scouts.nike.collector",
    "scouts.nike.parser",
    "scouts.nike.rules",
    "scouts.nike.scorer",

    "scouts.pokemon.alert_brief",
    "scouts.pokemon.alert_intelligence",
    "scouts.pokemon.alert_queue",
    "scouts.pokemon.alert_store",
    "scouts.pokemon.classifier",
    "scouts.pokemon.collector",
    "scouts.pokemon.collector_intelligence",
    "scouts.pokemon.consensus",
    "scouts.pokemon.enrichment",
    "scouts.pokemon.identity",
    "scouts.pokemon.internet_scout",
    "scouts.pokemon.investment_intelligence",
    "scouts.pokemon.parser",
    "scouts.pokemon.product_details",
    "scouts.pokemon.release_brief",
    "scouts.pokemon.release_calendar",
    "scouts.pokemon.release_store",
    "scouts.pokemon.rules",
    "scouts.pokemon.scorer",
    "scouts.pokemon.sources",
    "scouts.pokemon.state_tracker",
    "scouts.pokemon.structured_data",

    "scouts.tcg.classifier",
    "scouts.tcg.enrichment",
    "scouts.tcg.intelligence",
    "scouts.tcg.profiles",

    "scouts.lorcana",
    "scouts.lorcana.collector",
    "scouts.lorcana.internet_scout",
    "scouts.lorcana.parser",
    "scouts.lorcana.sources",

    "signals.base",
    "signals.collaboration",
    "signals.collector_interest",
    "signals.collector_value",
    "signals.exclusive",
    "signals.historical_pattern",
    "signals.investment_strategy",
    "signals.limited_release",
    "signals.official_source",
    "signals.reprint",
    "signals.restock",
    "signals.shock_drop",
    "signals.source_consensus",
    "scouts.one_piece.internet_scout",
]


def test_imports():
    for module in MODULES:
        importlib.import_module(
            module
        )